apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka-features
  namespace: knative-eventing
  annotations:
    knative.dev/example-checksum: "cf3393de"
data:
  _example: |-
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################
    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
    #
    # Controls whether the dispatcher should use the rate limiter based on the number of virtual replicas.
    # 1. Enabled: The rate limiter is applied.
    # 2. Disabled: The rate limiter is not applied.
    dispatcher-rate-limiter: "disabled"
    # Controls whether the dispatcher should record additional metrics.
    # 1. Enabled: The metrics are recorded.
    # 2. Disabled: The metrics are not recorded.
    dispatcher-ordered-executor-metrics: "disabled"
    # Controls whether the controller should autoscale consumer resources with KEDA
    # 1. Enabled: KEDA autoscaling of consumers will be setup.
    # 2. Disabled: KEDA autoscaling of consumers will not be setup.
    controller-autoscaler-keda: "disabled"
    # The Go text/template used to generate consumergroup ID for triggers.
    # The template can reference the trigger Kubernetes metadata only.
    triggers-consumergroup-template: "knative-trigger-{{ .Namespace }}-{{ .Name }}"
    # The Go text/template used to generate topics for Brokers.
    # The template can reference the broker Kubernetes metadata only.
    brokers-topic-template: "knative-broker-{{ .Namespace }}-{{ .Name }}"
    # The Go text/template used to generate topics for Channels.
    # The template can reference the channel Kubernetes metadata only.
    channels-topic-template: "knative-channel-{{ .Namespace }}-{{ .Name }}"
  dispatcher-rate-limiter: "disabled"
  dispatcher-ordered-executor-metrics: "disabled"
  controller-autoscaler-keda: "disabled"
  triggers-consumergroup-template: "knative-trigger-{{ .Namespace }}-{{ .Name }}"
  brokers-topic-template: "knative-broker-{{ .Namespace }}-{{ .Name }}"
  channels-topic-template: "knative-messaging-kafka.{{ .Namespace }}.{{ .Name }}"
